### ISSUE TITLE
I can't seem to connect to the server.

### ISSUE THREAD

**Issue by WalkerGauthier** [kartzcoder/SecureChat#2]
It may be my ip or my port either way . A simple walkthrough of the program would be great.

**Comment by kartzcoder** [comment]
Launch the project using NetBeans and follow the steps:
1. goto source packages -> com.securechar.gui -> right click on ServerGUI and start the server. You can use the default configuration and just start.
2. goto source packages -> com.securechar.gui -> right click on ClientGUI and run the client. Give the username as required and accept other default config and start.
3. repeat step 2 for another user so that you have 2 clients to talk to. exchange messages by pressing enter.
Note: default encryption used is AES.
Using the upload button you can send even files. 

Let me know your system configuration if you are still facing issues.
